"""Emit the ESP-IDF artifacts: model C array, op resolver, and runtime config.

`resolver_source` is the fix for a deployment blocker in the pre-refactor
notebook. Its firmware sketch registered eight operators by hand while the
converted model actually used thirteen, two of which
(``SPACE_TO_BATCH_ND``/``BATCH_TO_SPACE_ND``, emitted by the dilated depthwise
convolutions) the sketch had never heard of. `AllocateTensors()` would have
failed on the device. Generating the resolver from the converted model's own op
list means the firmware and the model cannot drift apart: the resolver is a
build artifact, not something a human maintains.

Deliberately TensorFlow-free -- it takes an op-name list, not a model -- so the
emission logic is unit-testable without a TF install.
"""

from __future__ import annotations

import json
from pathlib import Path

# TFLite builtin operator name -> MicroMutableOpResolver method.
# Extend as models grow; an unmapped op raises rather than being silently
# skipped, because a silently skipped op is a runtime failure on the device.
RESOLVER_METHODS: dict[str, str] = {
    "ADD": "AddAdd",
    "AVERAGE_POOL_2D": "AddAveragePool2D",
    "BATCH_TO_SPACE_ND": "AddBatchToSpaceNd",
    "CONCATENATION": "AddConcatenation",
    "CONV_2D": "AddConv2D",
    "DEPTHWISE_CONV_2D": "AddDepthwiseConv2D",
    "DEQUANTIZE": "AddDequantize",
    "EXPAND_DIMS": "AddExpandDims",
    "FULLY_CONNECTED": "AddFullyConnected",
    "LEAKY_RELU": "AddLeakyRelu",
    "LOGISTIC": "AddLogistic",
    "MAX_POOL_2D": "AddMaxPool2D",
    "MEAN": "AddMean",
    "MUL": "AddMul",
    "PACK": "AddPack",
    "PAD": "AddPad",
    "QUANTIZE": "AddQuantize",
    "RELU": "AddRelu",
    "RESHAPE": "AddReshape",
    "RSQRT": "AddRsqrt",
    "SHAPE": "AddShape",
    "SOFTMAX": "AddSoftmax",
    "SPACE_TO_BATCH_ND": "AddSpaceToBatchNd",
    "SPLIT": "AddSplit",
    "SQUEEZE": "AddSqueeze",
    "STRIDED_SLICE": "AddStridedSlice",
    "SUB": "AddSub",
    "SUM": "AddSum",
    "TRANSPOSE": "AddTranspose",
    "UNPACK": "AddUnpack",
}

# Not device operators. `DELEGATE` is how the *host* interpreter reports a
# delegated subgraph (XNNPACK on desktop); there is no such node in the model
# and TFLM has nothing to register for it. It showed up in the pre-refactor op
# dump and would have sent someone hunting for AddDelegate().
HOST_ONLY_OPS = {"DELEGATE"}

# Ops that ESP-NN has no optimized int8 kernel for. They still run, as reference
# C++, which on an ESP32-S3 is several times slower than the vectorized path --
# so a model that leans on them wastes the reason for choosing the S3.
NOT_ESP_NN_ACCELERATED = {
    "SPACE_TO_BATCH_ND",
    "BATCH_TO_SPACE_ND",
    "TRANSPOSE",
    "STRIDED_SLICE",
    "PACK",
    "UNPACK",
    "SPLIT",
}


def device_ops(ops: list[str]) -> list[str]:
    """Filter a host-reported op list down to operators that exist on device."""
    return sorted({o for o in ops if o not in HOST_ONLY_OPS})


def check_ops(ops: list[str]) -> dict[str, list[str]]:
    """Report unmapped and un-accelerated operators without raising.

    Call this before `resolver_source` in a notebook so the diagnosis is visible
    rather than arriving as an exception.
    """
    real = device_ops(ops)
    return {
        "ops": real,
        "unmapped": [o for o in real if o not in RESOLVER_METHODS],
        "not_accelerated": [o for o in real if o in NOT_ESP_NN_ACCELERATED],
    }


def resolver_source(ops: list[str], var: str = "resolver") -> str:
    """Generate the MicroMutableOpResolver declaration for exactly these ops.

    Registering only what the model uses saves roughly 30-50 KB of flash against
    AllOpsResolver, and the template parameter must be at least the number of
    registered ops or the registration silently fails at runtime.
    """
    real = device_ops(ops)
    unmapped = [o for o in real if o not in RESOLVER_METHODS]
    if unmapped:
        raise KeyError(
            f"no MicroMutableOpResolver method known for {unmapped}. Add them to "
            f"RESOLVER_METHODS after checking the TFLM header for the exact "
            f"spelling (micro_mutable_op_resolver.h) -- guessing the name gives a "
            f"compile error, and omitting the op gives a runtime failure."
        )

    lines = [
        f"// Generated by shahoshi.export.resolver_source for {len(real)} operators.",
        "// Do not hand-edit: regenerate when the model changes.",
        f"static tflite::MicroMutableOpResolver<{len(real)}> {var};",
    ]
    lines += [f"{var}.{RESOLVER_METHODS[o]}();" for o in real]

    slow = [o for o in real if o in NOT_ESP_NN_ACCELERATED]
    if slow:
        lines.append("")
        lines.append(
            "// WARNING: no ESP-NN int8 kernel for "
            + ", ".join(slow)
            + " -- these run as reference C++."
        )
    return "\n".join(lines)


def emit_c_array(
    blob: bytes,
    stem: str | Path,
    symbol: str = "g_movement_model_data",
    per_line: int = 12,
) -> tuple[Path, Path]:
    """Write `stem`.h and `stem`.cc holding `blob` as a 16-byte-aligned array.

    `alignas(16)` is required: TFLM reads the flatbuffer in place, and an
    unaligned model buffer faults or silently misparses on Xtensa.
    """
    stem = Path(stem)
    stem.parent.mkdir(parents=True, exist_ok=True)
    header, source = stem.with_suffix(".h"), stem.with_suffix(".cc")

    header.write_text(
        "#pragma once\n"
        "// Generated by shahoshi.export.emit_c_array. Do not hand-edit.\n"
        f"extern const unsigned char {symbol}[];\n"
        f"extern const unsigned int {symbol}_len;\n",
        encoding="utf-8",
    )

    with source.open("w", encoding="utf-8") as f:
        f.write(f'#include "{header.name}"\n\n')
        f.write(f"const unsigned int {symbol}_len = {len(blob)};\n")
        f.write(f"alignas(16) const unsigned char {symbol}[] = {{\n")
        for i in range(0, len(blob), per_line):
            f.write("  " + ", ".join(f"0x{b:02x}" for b in blob[i : i + per_line]) + ",\n")
        f.write("};\n")

    print(f"  wrote {header.name} / {source.name}  ({len(blob) / 1024:.1f} KB in .rodata)")
    return header, source


def write_config(
    path: str | Path,
    win: int,
    channels: int,
    fs: int,
    stride: int,
    classes: list[str],
    mean: list[float],
    std: list[float],
    thresholds: dict[str, float],
    extra: dict | None = None,
) -> Path:
    """Write the runtime config the firmware reads alongside the model."""
    hop_seconds = stride / fs
    cfg = {
        "win": int(win),
        "channels": int(channels),
        "fs": int(fs),
        "stride": int(stride),
        "hop_seconds": hop_seconds,
        "windows_per_hour": 3600.0 / hop_seconds,
        "classes": list(classes),
        "mean": [float(v) for v in mean],
        "std": [float(v) for v in std],
        "thresholds": {k: float(v) for k, v in thresholds.items()},
    }
    if extra:
        cfg.update(extra)

    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(cfg, indent=2), encoding="utf-8")
    print(f"  wrote {path.name}")
    return path


def normalization_source(mean: list[float], std: list[float]) -> str:
    """The frozen normalization constants, as a C snippet to paste into firmware."""
    if len(mean) != len(std):
        raise ValueError(f"mean has {len(mean)} entries, std has {len(std)}")
    fmt = lambda vs: ", ".join(f"{float(v):.6f}f" for v in vs)  # noqa: E731
    return (
        f"// Frozen at training time from the TRAIN split only.\n"
        f"static const float kMean[{len(mean)}] = {{{fmt(mean)}}};\n"
        f"static const float kStd[{len(std)}]  = {{{fmt(std)}}};\n"
    )


def firmware_notes(ops: list[str], arena: dict[str, float], config_name: str) -> str:
    """A short deployment checklist reflecting this specific exported model."""
    report = check_ops(ops)
    lines = [
        "Deployment checklist",
        "--------------------",
        f"  model in flash        : {arena['flash_kb']:.1f} KB",
        f"  largest single tensor : {arena['largest_tensor_kb']:.1f} KB",
        f"  operators registered  : {len(report['ops'])}",
        "",
        "  1. Start the arena at 100 KB, log interp.arena_used_bytes() after the",
        "     first Invoke(), then shrink the arena to that figure times ~1.1.",
        "  2. On the ESP32-S3 enable ESP-NN (CONFIG_NN_OPTIMIZATIONS=y) for 3-8x",
        "     faster int8 convolutions; the S3's vector unit is the reason to",
        "     prefer it over a plain ESP32 or a C3 for this workload.",
        f"  3. Normalization constants and thresholds live in {config_name}.",
        "  4. idf.py add-dependency \"espressif/esp-tflite-micro\"",
    ]
    if report["not_accelerated"]:
        lines += [
            "",
            "  WARNING: these operators have no ESP-NN int8 kernel and will run as",
            "  reference C++: " + ", ".join(report["not_accelerated"]),
        ]
    return "\n".join(lines)
